### ISSUE TITLE
AHRS Algorhitm and gravity removal

### ISSUE THREAD

**Issue by sara-pass** [xioTechnologies/Oscillatory-Motion-Tracking-With-x-IMU#13]
Hello, 
I'm using a NGIMU for a similar application and I would like to ask if I need to apply the AHRS algorhitm and remove gravity with the version of IMU that I'm using.
Moreover, is there a new version of the code adapted to NGIMU?
Thank you very much!

**Comment by xioTechnologies** [comment]
This is the repo you are looking for: [Oscillatory-Motion-Tracking-With-NGIMU](https://github.com/xioTechnologies/Oscillatory-Motion-Tracking-With-NGIMU)
