### ISSUE TITLE
Filtering accel data

### ISSUE THREAD

**Issue by brunocannavina** [xioTechnologies/Oscillatory-Motion-Tracking-With-x-IMU#7]
Why do you first integrate acceleration and then filter the speed and position?
Can I just filter the acceleration?

**Comment by xioTechnologies** [comment]
Velocity and position are high-pass filtered to remove integral drift.  The oscillatory motion of interest is assumed to be of a greater bandwidth than the drift.

**Comment by brunocannavina** [comment]
amazing project!
Just what I was looking for!
Thank you
