### ISSUE TITLE
NGIMU Port

### ISSUE THREAD

**Issue by habkorn** [xioTechnologies/Oscillatory-Motion-Tracking-With-x-IMU#9]
Greetings,

is there a way to port this code to be compatible with NGIMU hardware?
x-IMU hardware isn't available anymore on the website.

Main thing is that the CSV files created by the NGIMU Data Logger/Converter contains the time in the first column; the matlab script accepts a 'packet number'. This packet number may be a sequence of integers, but not all packet numbers are "1" - step from each other (i.e. gaps exist).

How does the packet number relate to time?

Kind regards,
Thomas

**Comment by xioTechnologies** [comment]
The NGIMU example is now available on github.

https://github.com/xioTechnologies/Oscillatory-Motion-Tracking-With-NGIMU
